name: upsystem
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi==0.115.0
      - sqlalchemy==2.0.36
      - uvicorn==0.30.6
      - pydantic==2.9.2
      - pytest==8.3.3
      - httpx==0.27.2
      - pytest-asyncio==0.24.0
